root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "apps", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html", "tsx"]
  exclude_regex = ["_test\\.go"]
